AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for FastAPI

Globals:
  Function:
    Runtime: python3.8
    CodeUri: app/
    Layers:
      - !Ref ExternalDepsLayer

Resources:
  # https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html
  ExternalDepsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: externalDepsLayer/python
      Description: Lambda layer to share python dependencies.
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.8

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Timeout: 30
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /
            Method: ANY
        NonRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessRestApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiURL:
    Description: "API endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
